[project]
name = "doppelganger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "openai>=2.14.0",
    "slack-bolt>=1.27.0",
    "zalgolib>=0.2.2",
]
